package:
  name: rg_gmp
  version: "6.1.0"

build:
  number: 1
  string: v1
source:
  fn: gmp-6.1.0.tar.bz2
  url: http://ftp.kaist.ac.kr/gnu/gnu/gmp/gmp-6.1.0.tar.bz2
  md5: 86ee6e54ebfc4a90b643a65e402c4048

about:
  home: http://gmplib.org/
  license: GPL 3

test:
  files:
    - test.c
