package:
  name: rg_valgrind
  version: "3.11.0"

build:
   number: 1
   string: v1

source:
  fn: valgrind-3.11.0.tar.bz2
  url: http://valgrind.org/downloads/valgrind-3.11.0.tar.bz2
  md5: 4ea62074da73ae82e0162d6550d3f129

about:
  home: http://valgrind.org/
  license: GNU General Public License, version 2.
