package:
  name: rg_gcc
  version: "4.9.3"

source:
  fn: gcc-4.9.3.tar.bz2
  url: http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-4.9.3/gcc-4.9.3.tar.bz2
  md5: 6f831b4d251872736e8e9cc09746f327

build:
  detect_binary_files_with_prefix: False # [not linux32]
  number: 1
  string: v1

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
