package:
  name: rg_mpfr
  version: "3.1.4"

build:
  number: 1
  string: v1

source:
  fn: mpfr-3.1.4.tar.bz2
  url: http://ftp.kaist.ac.kr/gnu/gnu/mpfr/mpfr-3.1.4.tar.bz2
  md5: b8a2f6b0e68bef46e53da2ac439e1cf4

requirements:
  build:
    - rg_gmp >=4.2.3
  run:
    - rg_gmp >=4.2.3

about:
  home: http://www.mpfr.org/
  license: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
