package:
  name: rg_python_base.ubuntu
  version: "2.7.13"

source:
  fn: Python-2.7.13.tar.xz
  url: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
  md5: 53b43534153bb2a0363f08bae8b9d990

requirements:
  build:
    - rg_patchelf >=0.8
    - rg_gcc  5.4.0
  run:
    - rg_gcc  >=5.4.0

build:
  no_link: bin/python
  number: 1
  string: gcc5

test:
  commands:
    - python -V               [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: general purpose programming language
